version: "3.9"

services:
  greenhouse-api:
    build: .
    environment:
    - AMBIENTE=PROD
    - PORT=:9000
    - WATER_PUMP_SUBSCRIBE=esp32/greenhouse/water_pump/pub
    - WATER_PUMP_PUBLISHER=esp32/greenhouse/water_pump/sub/
    - TEMPERATURE_SUBSCRIBE=esp32/greenhouse/temperature/pub
    - TEMPERATURE_PUBLISHER=esp32/greenhouse/temperature/sub/
    - AWS_ACCESS_KEY_ID=AKIAVE7U4U45RS6EVYBV
    - AWS_SECRET_ACCESS_KEY=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
    - AWS_REGION=us-east-1
    ports:
    - 9000:9000
    networks:
    - arduino

networks:
  arduino:
    driver: bridge